"""
Two-role credential gate for the personal tools — /api/auth/*.

Plutus is a single-user toolbench deployed on a public URL. Two people need
to get in for different reasons, so there are two credentials:

  OWNER  — full CRUD. The password is ``PLUTUS_APP_PASSWORD``, an env var on
           the API host. Rotating it means editing the environment, which is
           right for the root credential: it should not be changeable by
           anything the browser can reach.

  VIEWER — read-only. The password is generated by the owner from the app's
           Console, stored HASHED in ``app_access`` (migration 018), and
           shown in plaintext exactly once at rotation. It is meant to be
           shared, so it has to be rotatable at any time without a redeploy.

Security model:
  * The password is POSTed once to /api/auth/login and exchanged for a
    signed token ``<role>.<exp>.<sig>``. The browser stores only the token;
    neither password is persisted client-side or put in a URL.
  * The ROLE is inside the signed payload, so a viewer cannot edit their
    token into an owner token without the signing key.
  * Signing keys are derived from the credentials themselves:
      owner  key = f(PLUTUS_APP_PASSWORD)
      viewer key = f(PLUTUS_APP_PASSWORD, viewer_hash)
    So changing the owner password kills every session, and rotating the
    viewer password kills every viewer session — with no server-side session
    store to purge.
  * Viewers are refused every write verb (POST/PUT/PATCH/DELETE) on the
    personal routes. This is the real boundary: hiding buttons in the UI is
    a courtesy, this is the enforcement.
  * ``PROTECTED_PREFIXES`` behaviour when no owner password is set:
      - unset, non-prod -> open, so local dev needs no password.
      - unset, prod     -> 503; the gate is explicitly unconfigured rather
                           than silently absent.
    This mirrors the PLUTUS_ADMIN_TOKEN contract in ``admin_trigger``.
  * Market-data reads (/api/pools, /api/stocks, /api/snapshots, /api/scans)
    stay open: no personal data, and the production Edge Function serves the
    same rows unauthenticated anyway.

NOTE: no ``from __future__ import annotations`` here — FastAPI must resolve
the ``Request`` annotations of the callables defined inside
``register_auth_routes``, which stringified annotations would break.
"""
import hashlib
import hmac
import logging
import os
import secrets
import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# Every route family that reads or writes personal data. Prefix match on the
# request path, so sub-routes are covered automatically as they are added.
PROTECTED_PREFIXES: Tuple[str, ...] = (
    "/api/journal",
    "/api/expenses",
    "/api/sizing",
    "/api/networth",
    # Pool membership edits rewrite the universe every scan and view reads.
    "/api/universe",
)
# Deliberately NOT listed: /api/admin/trigger enforces its own dedicated
# PLUTUS_ADMIN_TOKEN, and its /status probe is public by design so the Sync
# tab can report whether triggers are configured. Double-gating it would
# break that contract without adding safety.

HEADER = "X-Plutus-Auth"
OWNER = "owner"
VIEWER = "viewer"
WRITE_METHODS = frozenset({"POST", "PUT", "PATCH", "DELETE"})
DEFAULT_TTL_DAYS = 30

# Brute-force damper: N failed logins inside WINDOW seconds -> 429 until the
# window rolls off. In-memory and per-process, which is enough for a
# single-instance personal API; it is a speed bump, not a WAF.
MAX_FAILURES = 8
FAILURE_WINDOW_SEC = 300
_failures: List[float] = []

# The viewer hash is read from Postgres on demand. Caching it keeps a DB
# round-trip off every gated request; rotation busts the cache in-process,
# and the short TTL bounds the staleness if a second instance ever rotates.
VIEWER_CACHE_TTL_SEC = 30
_viewer_cache: Dict[str, Any] = {"row": None, "at": 0.0}

# Shared-password alphabet: no I/O/0/1, so a password read off a screen or
# dictated over the phone does not come back wrong.
_PW_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
_PW_GROUPS = 4
_PW_GROUP_LEN = 4


# ---------------------------------------------------------------------------
# Config — env read per request (not cached) so a Render env edit applies on
# restart without a code change, matching admin_trigger.
# ---------------------------------------------------------------------------
def _password() -> str:
    return os.environ.get("PLUTUS_APP_PASSWORD", "").strip()


def _env() -> str:
    return os.environ.get("PLUTUS_ENV", "dev").strip() or "dev"


def _ttl_seconds() -> int:
    raw = os.environ.get("PLUTUS_AUTH_TTL_DAYS", "").strip()
    try:
        days = int(raw) if raw else DEFAULT_TTL_DAYS
    except ValueError:
        days = DEFAULT_TTL_DAYS
    return max(1, days) * 86400


def is_configured() -> bool:
    """True when an owner credential is set, i.e. the gate can actually lock."""
    return bool(_password())


def _secret(role: str, viewer_hash: Optional[str] = None) -> bytes:
    """
    Per-role signing key.

    Deriving from the credentials is deliberate: rotating a password
    invalidates its outstanding tokens for free. PLUTUS_AUTH_SECRET is
    optional and only adds entropy for a short owner password.
    """
    extra = os.environ.get("PLUTUS_AUTH_SECRET", "")
    material = f"plutus-auth-v2|{role}|{_password()}|{viewer_hash or ''}|{extra}"
    return hashlib.sha256(material.encode("utf-8")).digest()


# ---------------------------------------------------------------------------
# Password / token primitives (framework-free — unit-testable on their own)
# ---------------------------------------------------------------------------
def hash_password(candidate: str) -> str:
    """SHA-256 hex of a viewer password. Never store the plaintext."""
    return hashlib.sha256(candidate.strip().encode("utf-8")).hexdigest()


def generate_viewer_password() -> str:
    """A shareable, dictatable password: XXXX-XXXX-XXXX-XXXX (80 bits)."""
    groups = [
        "".join(secrets.choice(_PW_ALPHABET) for _ in range(_PW_GROUP_LEN))
        for _ in range(_PW_GROUPS)
    ]
    return "-".join(groups)


def check_owner_password(candidate: Any) -> bool:
    """Constant-time compare against PLUTUS_APP_PASSWORD."""
    expected = _password()
    if not expected or not isinstance(candidate, str):
        return False
    return hmac.compare_digest(candidate.strip().encode("utf-8"),
                               expected.encode("utf-8"))


def check_viewer_password(candidate: Any, viewer_hash: Optional[str]) -> bool:
    """Constant-time compare against the stored view-only hash."""
    if not viewer_hash or not isinstance(candidate, str) or not candidate.strip():
        return False
    return hmac.compare_digest(hash_password(candidate), viewer_hash)


def _sign(role: str, exp: int, viewer_hash: Optional[str] = None) -> str:
    return hmac.new(_secret(role, viewer_hash),
                    f"v2.{role}.{exp}".encode("utf-8"),
                    hashlib.sha256).hexdigest()


def issue_token(role: str, viewer_hash: Optional[str] = None,
                now: Optional[float] = None) -> Tuple[str, int]:
    """Mint a token for ``role``. Returns (token, expiry_unix)."""
    exp = int((now if now is not None else time.time()) + _ttl_seconds())
    return f"{role}.{exp}.{_sign(role, exp, viewer_hash)}", exp


def token_role(token: Any, viewer_hash: Optional[str] = None,
               now: Optional[float] = None) -> Optional[str]:
    """
    The role a token proves, or None if it proves nothing.

    ``viewer_hash`` is only consulted for viewer tokens; owner tokens verify
    with no database access at all, so the owner can still sign in when
    Supabase is unreachable.
    """
    if not isinstance(token, str):
        return None
    parts = token.strip().split(".")
    if len(parts) != 3:
        return None
    role, raw_exp, sig = parts
    if role not in (OWNER, VIEWER):
        return None
    try:
        exp = int(raw_exp)
    except ValueError:
        return None
    if exp <= (now if now is not None else time.time()):
        return None
    if role == VIEWER and not viewer_hash:
        return None          # view-only access is switched off
    expected = _sign(role, exp, viewer_hash if role == VIEWER else None)
    return role if hmac.compare_digest(sig, expected) else None


# ---------------------------------------------------------------------------
# Gate decision (framework-free)
# ---------------------------------------------------------------------------
def is_protected(path: str) -> bool:
    return any(path.startswith(p) for p in PROTECTED_PREFIXES)


def gate_refusal(path: str, method: str,
                 role: Optional[str]) -> Optional[Tuple[int, str]]:
    """
    Decide whether a request must be refused.

    Returns ``(status_code, message)`` when blocked, or ``None`` to proceed.
    """
    if not is_protected(path):
        return None
    if not is_configured():
        if _env() == "prod":
            return (503, "auth not configured: set PLUTUS_APP_PASSWORD")
        return None                       # local dev convenience
    if role is None:
        return (401, "sign in required")
    if role == VIEWER and method.upper() in WRITE_METHODS:
        return (403, "view-only access — this action is disabled")
    return None


def _throttled(now: Optional[float] = None) -> bool:
    """True when too many recent login failures — caller should 429."""
    t = now if now is not None else time.time()
    cutoff = t - FAILURE_WINDOW_SEC
    _failures[:] = [f for f in _failures if f > cutoff]
    return len(_failures) >= MAX_FAILURES


def _record_failure(now: Optional[float] = None) -> None:
    _failures.append(now if now is not None else time.time())


def _reset_failures() -> None:
    _failures.clear()


# ---------------------------------------------------------------------------
# Viewer credential storage (app_access, migration 018)
# ---------------------------------------------------------------------------
def invalidate_viewer_cache() -> None:
    _viewer_cache["row"] = None
    _viewer_cache["at"] = 0.0


def read_viewer_row(client: Any, *, force: bool = False,
                    now: Optional[float] = None) -> Dict[str, Any]:
    """
    The app_access singleton, cached briefly.

    Degrades to "view-only access is off" whenever the row cannot be read —
    a database blip or an un-applied migration 018 must never lock the owner
    out, and it must never accidentally let a viewer in.
    """
    t = now if now is not None else time.time()
    if not force and _viewer_cache["row"] is not None \
            and (t - _viewer_cache["at"]) < VIEWER_CACHE_TTL_SEC:
        return _viewer_cache["row"]
    row: Dict[str, Any] = {}
    try:
        res = (client.table("app_access").select("*").eq("id", 1)
               .limit(1).execute())
        rows = list(getattr(res, "data", None) or [])
        row = rows[0] if rows else {}
    except Exception as exc:  # noqa: BLE001
        logger.warning("app_access unreadable (view-only access off): %s", exc)
        row = {}
    _viewer_cache["row"] = row
    _viewer_cache["at"] = t
    return row


def viewer_hash_of(row: Dict[str, Any]) -> Optional[str]:
    h = (row or {}).get("viewer_hash")
    return h if isinstance(h, str) and h else None


def rotate_viewer_password(client: Any) -> Dict[str, Any]:
    """
    Mint a new view-only password, store its hash, return the plaintext.

    The plaintext is returned to the caller ONCE and never persisted. Every
    viewer token signed under the previous hash stops verifying the moment
    this lands.
    """
    password = generate_viewer_password()
    rotated_at = datetime.now(timezone.utc).isoformat()
    payload = {
        "id": 1,
        "viewer_hash": hash_password(password),
        "viewer_hint": password[:4],
        "rotated_at": rotated_at,
    }
    client.table("app_access").upsert(payload, on_conflict="id").execute()
    invalidate_viewer_cache()
    logger.info("auth: view-only password rotated")
    return {"password": password, "hint": payload["viewer_hint"],
            "rotated_at": rotated_at}


def disable_viewer_access(client: Any) -> None:
    """Switch view-only access off and kill every viewer session."""
    client.table("app_access").upsert(
        {"id": 1, "viewer_hash": None, "viewer_hint": None,
         "rotated_at": datetime.now(timezone.utc).isoformat()},
        on_conflict="id",
    ).execute()
    invalidate_viewer_cache()
    logger.info("auth: view-only access disabled")


# ---------------------------------------------------------------------------
# Routes + middleware
# ---------------------------------------------------------------------------
def register_auth_routes(app: Any, cli: Any) -> None:
    """
    Mount /api/auth/* and install the gate middleware.

    Call this BEFORE ``add_middleware(CORSMiddleware, ...)``: Starlette runs
    the most recently added middleware outermost, so adding CORS last keeps
    it wrapped around the gate and a 401/403 still carries the CORS headers
    the browser needs to surface the status instead of a network error.

    Args:
        app: FastAPI instance.
        cli: zero-arg callable returning the (injectable) supabase client;
             falls back to the module-level singleton when it returns None.
    """
    from fastapi import Body, HTTPException, Request
    from fastapi.responses import JSONResponse

    from plutus.adapters import supabase_client as sb

    def client() -> Any:
        return cli() or sb.get_client()

    def current_viewer_hash(*, force: bool = False) -> Optional[str]:
        try:
            return viewer_hash_of(read_viewer_row(client(), force=force))
        except Exception as exc:  # noqa: BLE001
            logger.warning("viewer hash lookup failed: %s", exc)
            return None

    def resolve_role(token: Any) -> Optional[str]:
        """
        Role proved by this token.

        Owner tokens verify without touching the database; only a token that
        claims the viewer role pays for the app_access lookup.
        """
        role = token_role(token)
        if role is not None:
            return role
        if isinstance(token, str) and token.startswith(f"{VIEWER}."):
            return token_role(token, current_viewer_hash())
        return None

    def require_owner(request: Request) -> None:
        """Owner-only routes. Unconfigured + non-prod = local dev owner."""
        if not is_configured():
            if _env() == "prod":
                raise HTTPException(status_code=503,
                                    detail="auth not configured: "
                                           "set PLUTUS_APP_PASSWORD")
            return
        if resolve_role(request.headers.get(HEADER)) != OWNER:
            raise HTTPException(status_code=403,
                                detail="owner access required")

    @app.middleware("http")
    async def _auth_gate(request: Request, call_next):
        if request.method == "OPTIONS":       # CORS preflight carries no header
            return await call_next(request)
        if not is_protected(request.url.path):
            return await call_next(request)   # no token work for open routes
        role = resolve_role(request.headers.get(HEADER))
        refusal = gate_refusal(request.url.path, request.method, role)
        if refusal is not None:
            status, message = refusal
            return JSONResponse(status_code=status, content={"error": message})
        return await call_next(request)

    # -- Session ------------------------------------------------------------
    @app.get("/api/auth/status")
    def auth_status(request: Request) -> dict:
        """Public: lets the frontend decide whether to show the lock screen."""
        role = resolve_role(request.headers.get(HEADER))
        configured = is_configured()
        return {
            "configured": configured,
            "required": configured or _env() == "prod",
            "authenticated": (not configured) or role is not None,
            # With no owner password set (local dev) everyone is the owner.
            "role": role or (None if configured else OWNER),
        }

    @app.post("/api/auth/login")
    def auth_login(payload: Dict[str, Any] = Body(...)) -> dict:
        if not is_configured():
            raise HTTPException(status_code=503,
                                detail="auth not configured: "
                                       "set PLUTUS_APP_PASSWORD")
        if _throttled():
            raise HTTPException(status_code=429,
                                detail="too many attempts — wait a few "
                                       "minutes and try again")
        candidate = (payload or {}).get("password")

        # One field, two credentials: whichever matches decides the role.
        if check_owner_password(candidate):
            _reset_failures()
            token, exp = issue_token(OWNER)
            return {"token": token, "role": OWNER, "expires_at": exp}

        vhash = current_viewer_hash(force=True)
        if check_viewer_password(candidate, vhash):
            _reset_failures()
            token, exp = issue_token(VIEWER, vhash)
            return {"token": token, "role": VIEWER, "expires_at": exp}

        _record_failure()
        logger.warning("auth: failed login attempt")
        raise HTTPException(status_code=401, detail="incorrect password")

    @app.get("/api/auth/verify")
    def auth_verify(request: Request) -> dict:
        """Cheap probe the frontend uses to drop a token the server rejects."""
        role = resolve_role(request.headers.get(HEADER))
        if is_configured() and role is None:
            raise HTTPException(status_code=401, detail="sign in required")
        return {"authenticated": True, "role": role or OWNER}

    # -- View-only credential (owner only) ----------------------------------
    @app.get("/api/auth/viewer")
    def viewer_state(request: Request) -> dict:
        """Whether view-only access is on, and which password is live.

        Returns the 4-character hint, never the password — the plaintext is
        shown once at rotation and is not recoverable afterwards."""
        require_owner(request)
        row = read_viewer_row(client(), force=True)
        return {
            "enabled": viewer_hash_of(row) is not None,
            "hint": row.get("viewer_hint"),
            "rotated_at": row.get("rotated_at"),
        }

    @app.post("/api/auth/viewer/rotate")
    def viewer_rotate(request: Request) -> dict:
        """Generate and store a new view-only password; return it once."""
        require_owner(request)
        try:
            return rotate_viewer_password(client())
        except HTTPException:
            raise
        except Exception as exc:  # noqa: BLE001
            logger.exception("viewer rotation failed")
            raise HTTPException(status_code=502, detail=str(exc))

    @app.delete("/api/auth/viewer")
    def viewer_disable(request: Request) -> dict:
        """Switch view-only access off; every shared session dies at once."""
        require_owner(request)
        try:
            disable_viewer_access(client())
        except HTTPException:
            raise
        except Exception as exc:  # noqa: BLE001
            logger.exception("disabling view-only access failed")
            raise HTTPException(status_code=502, detail=str(exc))
        return {"enabled": False}
